# Generated by Django 4.0.4 on 2022-07-03 22:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_alter_category_id_alter_entry_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
