# Generated by Django 4.0.4 on 2022-08-05 01:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_alter_entry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
